snap: Fix missing screenshots due to GdkPixbuf error
This is a work-around for the broken Gdk Pixbuf in the Gnome SDK

  https://github.com/ubuntu/gnome-sdk/issues/357

that would manifest in appstream-generator's failure to generate
screenshots with

  ERROR: The currently used GdkPixbuf does not seem to support all image
  formats we require to run normally (png/svg/jpeg). This may be a problem
  with your installation of appstream-generator or gdk-pixbuf.

It merely runs appstream-generator with GDK_PIXBUF_MODULE{DIR,_FILE}
pointing to the libraries staged in this snap.

Another attempt to address this was to remove the Gnome extension (which
ultimately enforces its own GDK_PIXBUF_*), but it encountered its own issues:

  https://github.com/ximion/appstream-generator/issues/172